# This workflow will build a Java project with Maven... 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Note - This action is temporary being used to help drive a GitOps trial and will be removed in the future

# Updated with custom plugin/action (...)

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *'

# The jobs...
jobs:
      
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # Checkout the source
    - name: Login to DockerHub...
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker image
      run:  |
        docker build . -f docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/jenkinsdsl:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jenkinsdsl:latest
    
    # Action to get the digest...
    - name: GitOps Helm Chart Update(s)
      uses: joshi-ashutosh/actions/productmanifest@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        gitops-repo-url: https://github.com/joshi-ashutosh/sample-repo
        manifest-file: helm/dev/values.yaml
        github-username: ${{ secrets.MY_GITHUB_ACTOR }}
        github-email: ${{ secrets.MY_GITHUB_EMAIL }}
        image-list: jenkinscd-framework-deployment:${{ secrets.DOCKERHUB_USERNAME }}/jenkinsdsl:latest
        git-token: ${{ secrets.MY_GITHUB_TOKEN }}
        registry-server: docker.io
        docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}

# End of job
