on: [push]
 
jobs:
   custom_test:
     runs-on: ubuntu-latest
     name: Test action locally 
     steps:
       - name: Helm Push 
         uses: joshi-ashutosh/actions/productmanifest@main
         id: productmanifest
         env:
           API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
           API_ACTOR_GITHUB: ${{ secrets.MY_GITHUB_ACTOR }}
           EMAIL: ashutoshjoshi.mit@gmail.com
         with:
           gitops-repo-url: https://github.com/joshi-ashutosh/sample-repo
           manifest-file: helm/dev/values.yaml
           github-username: ${{ env.API_ACTOR_GITHUB }}
           github-email: ${{ env.EMAIL }}
           image-list: helm:wscs-deployment:01909
           git-token: ${{ env.API_TOKEN_GITHUB }}
           registry-server: docker.io
           docker-username: username
           docker-passwd: passwd
