name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The jobs...
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checkout the source
    - name: Login to DockerHub...
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker image
      run:  |
        docker build . -f docker/Dockerfile -t joshi-ashutosh/jenkinsdsl:latest
        docker push joshi-ashutosh/jenkinsdsl:latest
    
    # Action to get the digest...
    - name: GitOps Helm Chart Update(s)
      uses: joshi-ashutosh/actions/productmanifest@main
      env:
        API_TOKEN_GITHUB: ${{ MY_GITHUB_TOKEN }}
      with:
        gitops-repo-url: https://github.com/joshi-ashutosh/sample-repo
        manifest-file: helm/dev/values.yaml
        github-username: ${{ secrets.MY_GITHUB_ACTOR }}
        github-email: ${{ secrets.MY_GITHUB_EMAIL }}
        image-list: jenkinscd-framework-deployment:joshi-ashutosh/jenkinsdsl:latest
        git-token: ${{ secrets.MY_GITHUB_TOKEN }}
        registry-server: docker.io
        docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
